### ISSUE TITLE
Anything new?

### ISSUE THREAD

**Issue by loic001** [nengo/nengo_detailed_neurons#4]
Hello,

First of all thank you for this repo!

Is that repo still on? Any improvements since then? Are there other resources about implementing compartmental models with Nengo? (with or without NEURON)

I would be interested in developing neurons population models that would be able to perform complex tasks (as Nengo knows it) but with compartmental neurons with a spatially extended morphology. Any suggestions?

Thanks a lot!

**Comment by psipeter** [comment]
Hello!

I suspect that Jan no longer monitors this repo, but (building off the methods here) I have spent the last few years playing with Nengo networks built from compartmental neuron models (implemented in NEURON). The repo is https://github.com/psipeter/detailed_neurons. It's still a work-in-progress, so documentation and examples are limited. But there are many applications to complex tasks that I'd like to explore! Feel free to start a thread or send me an email, and I can help you get up to speed with what I've put together so far.

**Comment by loic001** [comment]
Wow great, thank you very much! I'll take a look around and I'll be sure to get back to you!
